### ISSUE TITLE
Cannot be used from Azure DevOps CI/CD pipeline

### ISSUE THREAD

**Issue by dickvdm** [madskristensen/PrivateGalleryCreator#13]
Call PrivateGalleryCreator.exe from Azure DevOps CI/CD pipeline:

<snippet from the log:>
_feed.xml generated successfully
Press any key to close...

Unhandled Exception: System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected from a file. Try Console.Read.
    at System.Console.ReadKey(Boolean intercept)
    at PrivateGalleryCreator.Program.Main(String[] args)_

Workaround in the pipeline can be to Ignore $LASTEXITCODE.

Better would be to code fix this.

Replace: _Console.ReadKey(true);_
with:       _Console.Read();_

**Comment by Andree2** [comment]
There is the (undocumented) "--terminate" option to not wait for any input.

**Comment by madskristensen** [comment]
Use the `--terminate` option to kill the progress

**Comment by dickvdm** [comment]
--terminate does the trick. Thx!

**Comment by OJacot-Descombes** [comment]
Just as an info: I set up my Visual Studio post-build event command line like this (works well):
```
xcopy "$(ProjectDir)$(OutDir)MyExtension.vsix" "C:\Users\...\Private_VSIX_Feed" /Y
C:\Users\...\Private_VSIX_Feed\PrivateGalleryCreator.exe --terminate
```
Then menu `Extensions > Manage Extensions`, then `Change your settings for Extensions > Add`:

Name: `My Private VSIX Feed`

URL: `file:///C:/Users/.../Private_VSIX_Feed/feed.xml`
