### ISSUE TITLE
Path to vsix files should be relative to feed.xml file

### ISSUE THREAD

**Issue by BackToTheCrm** [madskristensen/PrivateGalleryCreator#19]
Hello,

First of all, thank you for this useful tool !

As an improvement, I suggest to add an option to generate relative path instead of absolute path in  feed.xml file.
For example, in my team we created a private gallery thanks to your tool synchronized with a OneDrive folder, however everyone have a different configuration and this result in wrong path.
So we manually updated the feed.xml with relative path in order to solve this issue.

Have a lovely day !

**Comment by ggaller** [comment]
Hi @BackToTheCrm!
Have you try `--source` flag for this case?
For example, if set `--source=".\"` then the result should be `.\Extension.vsix`.
Or if use `--recursive` and subfolders then expected result should be `.\folder1\Extension.vsix`.
This is what you need?

**Comment by BackToTheCrm** [comment]
Hi @ggaller, 
I didn't think of that ! 
I tried and it seems that your solution works with a slight modification : the quotes must be removed.

So the following command does exaclty what I wanted : `PrivateGalleryCreator.exe --source=.\`

Thank you for your help !
