### ISSUE TITLE
Adding configuration options --input, --output and --recursive

### ISSUE THREAD

**Issue by psmulovics** [madskristensen/PrivateGalleryCreator#4]
To aid automatic usage of the tool from CI, a few options would be useful (all of them likely only require modification of Program.cs):

--input : to specify the dir_ to look at
--output : to specify the folder and filename of the feed.xml created
--recursive : to specify whether I need to remove TopDirectoryOnly and to dive into subdirectories as well.

If there is no concern of these changes, I'd do a PR for these.

**Comment by psmulovics** [comment]
I take this as no concern, @madskristensen , so I'd submit PR for these.

**Comment by madskristensen** [comment]
That would be awesome. These are great additions

**Comment by psmulovics** [comment]
Figured out I'd need to add an --absolutePath setting too:

--absolutePath: produces absolute path for icons the for packages

**Comment by madskristensen** [comment]
Perhaps just change it to always use absolute paths. I can't think of a reason to make it configurable, can you?

**Comment by psmulovics** [comment]
You know, backward compatibility 💯

**Comment by madskristensen** [comment]
why isn't it backwards compatible?

**Comment by psmulovics** [comment]
Eg if now you run, you get relative paths, you run after my change, you get absolute path?

**Comment by psmulovics** [comment]
ok, finished the changes at last (got little distracted in the middle), would submit PR this week
